project:
  type: website
  output-dir: docs

variables:
  author_default: Greg Brooks

website:
  title: "Prospect Research Toolkit"
  description: A prospect research resource library created by Greg Brooks and Apra Utah
  site-url:  https://prospectresearchtoolkit.github.io/ProspectResearchToolkit/
  open-graph: true
  back-to-top-navigation: true
  page-navigation: true

  navbar:
    background: secondary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Field Notes"
        href: field_notes.qmd
      - text: "Inventory"
        href: inventory_manifest.qmd
      - text: "A-Z List"
        href: inventory_table_version.qmd
      - text: "Software Dashboard"
        href: toolkit_dashboard1.qmd
      
  announcement: 
    content: "**Welcome!** - this website is a work in progress, and some pages/features may be empty, unfinished, or broken. Thank you for your patience!" 
    position: below-navbar 
    type: info
    icon: info-square-fill

  reader-mode: false
  page-footer: 
    left: " "

extensions:
  badge:
    - key: toolbadge
      color: "#9E5829"
    

format:
  html:
    respect-user-color-scheme: true
    theme: simplex

    css: styles.css
    toc: true



