project:
  type: website
  output-dir: docs

variables:
  author_default: Greg Brooks

website:
  title: "Prospect Research Toolkit"
  description: A prospect research resource library created by Greg Brooks and Apra Utah
  site-url:  https://prospectresearchtoolkit.github.io/ProspectResearchToolkit/
  open-graph: true
  back-to-top-navigation: true

  navbar:
    background: secondary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Field Guide"

  announcement: 
    content: "**Welcome!** - this website is a work in progress, and some pages/features may be empty, unfinished, or broken. Thank you for your patience!" 
    position: below-navbar 
    type: info
    icon: info-square-fill

  reader-mode: false
  page-footer: 
    left: "Website updated: 10/9/2025"

    
  sidebar:
    style: "docked"
    search: false
    contents: 
      - section: "Tools"
        contents: 
          - templates.qmd
          - toolkit_dashboard1.qmd
      - section: "Education"
        contents: 
          - tutorials.qmd
          - blog.qmd
      - section: "External Resources"
        contents:
          - free_resources_links.qmd

format:
  html:
    respect-user-color-scheme: true
    theme: simplex

    css: styles.css
    toc: true



